CREATE DATABASE VIKRAM_SHOPPINGDB

USE VIKRAM_SHOPPINGDB;

CREATE TABLE CUSTOMER
(
    CUSTOMERID INT,
	CUSTOMERNAME VARCHAR(10),
	EMAIL VARCHAR(20),
	AGE INT,
	DOB DATETIME
	)

		CREATE TABLE ORDERS
	( 
	      ORDERID INT,
		  ORDERDATE DATETIME,
		  CUSTOMERID INT
		  )


  ALTER TABLE CUSTOMER
  ADD PHONE VARCHAR(10)

 

  ALTER TABLE CUSTOMER
  ALTER COLUMN CUSTOMERNAME VARCHAR(20) NOT NULL

   SELECT*FROM CUSTOMER
	
  ALTER TABLE CUSTOMER
  DROP COLUMN DOB

  DROP TABLE CUSTOMER
